#! /usr/bin/env python3

"""

Aligns a subset of FASTQ files against the Gopherus flavomarginatus
reference genome using minimap2. Reads the file list generated by
01_subsample.py and produces a sorted and indexed BAM file.

Usage:
    python3 02_align_reads.py small
    python3 02_align_reads.py large
"""

import os
import sys
from genome_mapping_utils import run_command, validate_file, extract_sample_name


# Define paths
REFERENCE = "/hosted/biosc/SchwartzLab/Nanopore/GopherTortoise/Gopherus_flavomarginatus_Ref_Genome/GCF_025201925.1_rGopFla2.mat.asm_genomic.mmi"
FILE_LISTS = {
    "small": "/scratch/amf0120/GT_7.4_B/small_subset_files.txt",
    "large": "/scratch/amf0120/GT_7.4_B/large_subset_files.txt"
}
OUTPUT_DIRS = {
    "small": "/scratch/amf0120/GT_7.4_B/Mapped_reads/small_subset",
    "large": "/scratch/amf0120/GT_7.4_B/Mapped_reads/large_subset"
}


def read_file_list(file_list_path):
    """
    Read a list of FASTQ file paths from a text file generated
    by 01_subsample.py.

    Parameters
    ----------
    file_list_path : str
        Path to the text file containing FASTQ file paths.

    Returns
    -------
    list
        List of FASTQ file paths.

    Examples
    --------
    >>> files = read_file_list("/scratch/amf0120/GT_7.4_B/small_subset_files.txt")
    >>> print(len(files))
    13
    """
    validate_file(file_list_path)
    with open(file_list_path, 'r') as f:
        files = [line.strip() for line in f if line.strip()]
    print(f"Read {len(files)} files from {file_list_path}")
    return files


def align_reads(fastq_files, reference, output_dir, subset_name):
    """
    Align FASTQ files to the reference genome using minimap2 and
    sort and index the output BAM file using samtools.

    Parameters
    ----------
    fastq_files : list
        List of FASTQ file paths to align.
    reference : str
        Path to the minimap2 reference index (.mmi).
    output_dir : str
        Path to the output directory for the BAM file.
    subset_name : str
        Name of the subset being aligned (small or large).

    Returns
    -------
    str
        Path to the sorted and indexed BAM file.

    Examples
    --------
    >>> bam = align_reads(files, reference, output_dir, "small")
    >>> print(bam)
    '/scratch/amf0120/GT_7.4_B/Mapped_reads/small_subset/FBE04231_small.bam'
    """
    sample_name = extract_sample_name(fastq_files[0])
    bam_file = os.path.join(output_dir, f"{sample_name}_{subset_name}.bam")
    fastq_string = " ".join(fastq_files)

    print(f"Aligning {len(fastq_files)} files to reference genome...")
    run_command(
        f"minimap2 -ax map-ont --secondary=no -t 8 {reference} {fastq_string} "
        f"| samtools sort -o {bam_file}"
    )

    validate_file(bam_file)
    print(f"BAM file created: {bam_file}")

    print("Indexing BAM file...")
    run_command(f"samtools index {bam_file}")
    print(f"Indexing complete: {bam_file}.bai")

    return bam_file


def main():
    """
    Align either the small or large subset of FASTQ files to the
    Gopherus flavomarginatus reference genome.
    """
    if len(sys.argv) != 2 or sys.argv[1] not in ["small", "large"]:
        print("Usage: python3 02_align_reads.py small")
        print("       python3 02_align_reads.py large")
        sys.exit(1)

    subset = sys.argv[1]

    print(f"Starting alignment for {subset} subset...")
    print(f"Reference: {REFERENCE}")

    fastq_files = read_file_list(FILE_LISTS[subset])
    validate_file(REFERENCE)

    bam_file = align_reads(fastq_files, REFERENCE, OUTPUT_DIRS[subset], subset)

    print(f"Alignment complete!")
    print(f"Output BAM: {bam_file}")


if __name__ == '__main__':
    main()
